Catchup archive
Sorien/plugin.video.sl pull request #64
Opened 2020-11-03 15:19 UTC by panda7789

Místo vyhledávání programu podle času a složitého dopočítávání jsem využil lodId který Skylink k EPG přidává.
Mělo by se jednat o unikátní označení pořadu, takže zpětné přehrávání přímo z EPG funguje i dost rychle.
Také jsem se pokusil udělat aby addon byl kompatibilní s Kodi Matrix.

Vyzkoušel jsem na windows s nainstalovanými oběma verzemi (18.9 a 19) a vše vypadá funkční.

Upravil jsem branch Sorien/catchup-archive, ale nemůžu přidávat do již běžícího pull requestu.
Nevím jestli jsem pull request do branche ze které již je pull request je dobrý nápad. Kdyžtak se prosím ozvěte a já to udělám přímo na mastra 😃

2020-11-03 16:37 UTC, Sorien approved these changes
lgtm, nemam ziadne vyhrady, ale neviem to otestovat, @cache-sk ak by sa ti to chcelo testnut ak nie mergnem to v priebehu par dni 

este ze som dokopal maintainera iptvsimple pridat "catchup_id" :D

2020-11-03 19:33 UTC, Sorien commented
@panda7789 ako stabilny je ten catchup v kodi? lebo najprv to behalo v pohode ale naposledy ked som to skusal tak to hodne crashovalo kodi.

2020-11-04 09:35 UTC, cache-sk commented
Som rad, ze pridal niekto dalsi. Ked som videl ako postupne menia api (chcel som zapracovat novu kniznicu) tak som sa obaval ze si na to budem musiet vziat dovolenku 😊 Otestovane na 18.8 a 19.0-ALPHA2, to co fungovalo funguje dalej, takze to vklude moze ist von, nezabudnite posunut verziu v addon.xml hore.

TODO (len poznamky, nie ze teraz treba):
- mne sa to catchup nepodarilo rozbehat, pozeral som to teraz prvy krat, vzdy mi to pusti live.. chcelo by to navod pre ludi co nemaju cas 😂
- potom asi preskumat, ci sa to nastavenie podla navodu da aj zautomatizovat (a doplnit do pisc.py)
- epg by sa asi koli catchup malo generovat od -7 dni?
- zaroven treba podchytit ak by sa niekto cez catchup snazil prehrat program, ktory uz v archive nieje
- mozno preskumat aj prehravanie prave beziaceho programu od zaciatku (vsimol som si tam prepinatko v catchup ci to podporovat alebo nie)
- pridam poistku do skins.py - na 18.8 to stale funguje, na 19+ nie a koli catchup to nebude potrebne uz

2020-11-06 18:42 UTC, Sorien requested changes

2020-11-06 18:42 UTC, Sorien commented on addon.xml
>  <addon id="plugin.video.sl" version="1.6.7" name="Skylink Live TV" provider-name="Sorien, cache-sk">
```suggestion
<addon id="plugin.video.sl" version="1.7.0" name="Skylink Live TV" provider-name="Sorien, cache-sk">
```

2020-11-07 10:17 UTC, merged